// Netlify Function serving the ATHLORA API at /api/*.
// The bundle is generated by `npm run build` (Netlify runs it on every deploy).
import handler from '../dist/api-bundle.mjs';

export default async (req) => handler(req);

export const config = { path: '/api/*' };
